<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Laptop;
use AppBundle\Entity\LaptopComments;

/**
 * commentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LaptopCommentsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByLaptopId($id)
    {
        return $this->createQueryBuilder('comment')
            ->where('comment.laptop = :equal')
            ->setParameter('equal', $id)
            ->getQuery()
            ->getArrayResult();
    }

    /**
     * @param Laptop $laptop
     * @return LaptopComments[]
     */
    public function findAllRecentNotesForGenus(Laptop $laptop)
    {
        return $this->createQueryBuilder('laptop_comments')
            ->andWhere('laptop_comments.laptop = :laptop')
            ->setParameter('laptop', $laptop)
            ->andWhere('laptop_comments.createdAt > :recentDate')
            ->setParameter('recentDate', new \DateTime('-3 months'))
            ->orderBy('laptop_comments.createdAt', 'DESC')
            ->getQuery()
            ->execute();
    }
}
