<?php

namespace AppBundle\Repository;

/**
 * LaptopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LaptopRepository extends \Doctrine\ORM\EntityRepository
{
    public function findActive()
    {
        return $this->createQueryBuilder('laptop')
            ->where('laptop.isActive = :active')
            ->setParameter('active', true)
            ->getQuery()
            ->getResult();
    }
}
