<?php

namespace AppBundle\Repository;

/**
 * tabletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tabletRepository extends \Doctrine\ORM\EntityRepository
{
}
