<?php

namespace AppBundle\Repository;

/**
 * TabletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TabletRepository extends \Doctrine\ORM\EntityRepository
{
    public function findActive()
    {
        return $this->createQueryBuilder('tablet')
            ->where('tablet.isActive = :active')
            ->setParameter('active', true)
            ->getQuery()
            ->getResult();
    }
}
